#= require ./store
#= require_tree ./ember_crm/models
#= require_tree ./ember_crm/controllers
#= require_tree ./ember_crm/views
#= require_tree ./ember_crm/helpers
#= require_tree ./components
#= require_tree ./ember_crm/templates
#= require_tree ./ember_crm/routes
#= require ./ember_crm/router
#= require_self
